### ISSUE TITLE
Voiceid - cant find good enough voice

### ISSUE THREAD

**Issue by Anubi5555** [Akul-AI/rlvoice#1]
- Hi, recently  moved from pyttx3.

- MacOS/M1

- I am working on a voice assistant but can't find a decent voice, I tried changing voice id but that does not change the gender, that changes the whole voice including language, gender and sometimes wierd efects. 

``` sh
engine = rlvoice.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[100].id)
```

- So how can I find normal and clear english voice and if not then how can I download voice and run it instead?
Tnx in advance, hope I was clear enough.

**Comment by Akul2010** [comment]
I don't think there are a lot of voices that NSSS (default MacOS speech engine) can support. I also don't think it is possible to upload custom voices to that engine. What voice IDs have you tried so far?

**Comment by Akul2010** [comment]
I am looking into adding support for another MacOS-compatible engine, as the current code is known to be extremely buggy.

**Comment by Anubi5555** [comment]
I tried IDs 0 to 10 and then 20, 30, 40, 50, 60, 70, 80, 90 and 91-102. 
Sometimes they are the same as previous ones but all of them are hard to understand or just not made for english language.

**Comment by Akul2010** [comment]
I think this is just a MacOS issue. As I said, I am looking into making another speech engine available for MacOS.
