### ISSUE TITLE
`save_to_file` does not work on M1 Mac

### ISSUE THREAD

**Issue by LilithHafner** [Akul-AI/rlvoice#2]
I ran this code in a repl and it failed to produce a file:
```
>>> import rlvoice
>>> engine = rlvoice.init() 
>>> engine.save_to_file("this is a test", "name.mp3")
>>> engine.runAndWait() # No file nor error is produced
>>> engine.say("this is a test")
>>> engine.runAndWait() # Speaks
```
Similar issues have been reported in a few other places:
https://github.com/nateshmbhat/pyttsx3/issues/171
https://stackoverflow.com/questions/67625515/not-able-to-write-files-from-pyttsx3
https://www.reddit.com/r/learnpython/comments/zol87o/pyttsx3_will_not_save_mp3_tts_file/

**Comment by Akul2010** [comment]
Ok, try this code:
`
import rlvoice
engine=rlvoice.init()
engine.save_to_file('this is a test', 'name.mp3')
engine.runAndWait()
`
Basically, the problem was that you used the `runAndWait`  method too many times. The `runAndWait` method just tells `rlvoice` to run whatever rlvoice-related code was used, so you don't need to use it more than once.

**Comment by LilithHafner** [comment]
I just tried the code you posted and it did not produce any file.

As an aside, it would be odd if
```
import rlvoice

engine=rlvoice.init()
engine.save_to_file('this is a test', 'name.mp3')
engine.runAndWait()
```
produced a file and
```
import rlvoice

engine=rlvoice.init()
engine.save_to_file('this is a test', 'name.mp3')
engine.runAndWait()
engine.say("this is a test")
engine.runAndWait()
```
did not, because `runAndWait` blocks so this would require the final two lines of the later example to _delete_ the file produced in the first 4.

**Comment by Akul2010** [comment]
I have tested on my Windows 11 machine and WSL (as best as I could), and they both work. I haven't yet figured out how to test for Mac, though I don't think they are too different. The code I have provided works, and it gives a working mp3 file.
